### ISSUE TITLE
Lovelace cards

### ISSUE THREAD

**Issue by geordiegits** [dadge/awesome_thermostat#1]
Hi Dadge
Great project,
Is there an accompanying Lovelace frontend card for this? Similar to the Lovelace simple thermostat card via HACS

also can the motion sensor be combined with the open window function 

Thanks

**Comment by dadge** [comment]
Hello geordiegits, 

thanks a lot for your feedback!
Regarding the card I use the classic thermostat, it does the job as you can set the temperature and the preset mode with it.
For your second question, yes it totally can be combined, I use it in my children rooms as I want only to heat when they are onside and on another hand I want to open the window to have fresh air without taking care of the heater. It works fine in all use cases.

regards,
